# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rengaj/Documents/PAGE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rengaj/Documents/PAGE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rengaj/Documents/PAGE/CMakeFiles /home/rengaj/Documents/PAGE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rengaj/Documents/PAGE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PAGE.out

# Build rule for target.
PAGE.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PAGE.out
.PHONY : PAGE.out

# fast build rule for target.
PAGE.out/fast:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/build
.PHONY : PAGE.out/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/page_debug.o: src/page_debug.cpp.o
.PHONY : src/page_debug.o

# target to build an object file
src/page_debug.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_debug.cpp.o
.PHONY : src/page_debug.cpp.o

src/page_debug.i: src/page_debug.cpp.i
.PHONY : src/page_debug.i

# target to preprocess a source file
src/page_debug.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_debug.cpp.i
.PHONY : src/page_debug.cpp.i

src/page_debug.s: src/page_debug.cpp.s
.PHONY : src/page_debug.s

# target to generate assembly for a file
src/page_debug.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_debug.cpp.s
.PHONY : src/page_debug.cpp.s

src/page_dof.o: src/page_dof.cpp.o
.PHONY : src/page_dof.o

# target to build an object file
src/page_dof.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_dof.cpp.o
.PHONY : src/page_dof.cpp.o

src/page_dof.i: src/page_dof.cpp.i
.PHONY : src/page_dof.i

# target to preprocess a source file
src/page_dof.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_dof.cpp.i
.PHONY : src/page_dof.cpp.i

src/page_dof.s: src/page_dof.cpp.s
.PHONY : src/page_dof.s

# target to generate assembly for a file
src/page_dof.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_dof.cpp.s
.PHONY : src/page_dof.cpp.s

src/page_graphics.o: src/page_graphics.cpp.o
.PHONY : src/page_graphics.o

# target to build an object file
src/page_graphics.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_graphics.cpp.o
.PHONY : src/page_graphics.cpp.o

src/page_graphics.i: src/page_graphics.cpp.i
.PHONY : src/page_graphics.i

# target to preprocess a source file
src/page_graphics.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_graphics.cpp.i
.PHONY : src/page_graphics.cpp.i

src/page_graphics.s: src/page_graphics.cpp.s
.PHONY : src/page_graphics.s

# target to generate assembly for a file
src/page_graphics.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_graphics.cpp.s
.PHONY : src/page_graphics.cpp.s

src/page_joint.o: src/page_joint.cpp.o
.PHONY : src/page_joint.o

# target to build an object file
src/page_joint.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_joint.cpp.o
.PHONY : src/page_joint.cpp.o

src/page_joint.i: src/page_joint.cpp.i
.PHONY : src/page_joint.i

# target to preprocess a source file
src/page_joint.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_joint.cpp.i
.PHONY : src/page_joint.cpp.i

src/page_joint.s: src/page_joint.cpp.s
.PHONY : src/page_joint.s

# target to generate assembly for a file
src/page_joint.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_joint.cpp.s
.PHONY : src/page_joint.cpp.s

src/page_matrix.o: src/page_matrix.cpp.o
.PHONY : src/page_matrix.o

# target to build an object file
src/page_matrix.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_matrix.cpp.o
.PHONY : src/page_matrix.cpp.o

src/page_matrix.i: src/page_matrix.cpp.i
.PHONY : src/page_matrix.i

# target to preprocess a source file
src/page_matrix.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_matrix.cpp.i
.PHONY : src/page_matrix.cpp.i

src/page_matrix.s: src/page_matrix.cpp.s
.PHONY : src/page_matrix.s

# target to generate assembly for a file
src/page_matrix.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_matrix.cpp.s
.PHONY : src/page_matrix.cpp.s

src/page_mesh.o: src/page_mesh.cpp.o
.PHONY : src/page_mesh.o

# target to build an object file
src/page_mesh.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_mesh.cpp.o
.PHONY : src/page_mesh.cpp.o

src/page_mesh.i: src/page_mesh.cpp.i
.PHONY : src/page_mesh.i

# target to preprocess a source file
src/page_mesh.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_mesh.cpp.i
.PHONY : src/page_mesh.cpp.i

src/page_mesh.s: src/page_mesh.cpp.s
.PHONY : src/page_mesh.s

# target to generate assembly for a file
src/page_mesh.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_mesh.cpp.s
.PHONY : src/page_mesh.cpp.s

src/page_parser.o: src/page_parser.cpp.o
.PHONY : src/page_parser.o

# target to build an object file
src/page_parser.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_parser.cpp.o
.PHONY : src/page_parser.cpp.o

src/page_parser.i: src/page_parser.cpp.i
.PHONY : src/page_parser.i

# target to preprocess a source file
src/page_parser.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_parser.cpp.i
.PHONY : src/page_parser.cpp.i

src/page_parser.s: src/page_parser.cpp.s
.PHONY : src/page_parser.s

# target to generate assembly for a file
src/page_parser.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_parser.cpp.s
.PHONY : src/page_parser.cpp.s

src/page_texture.o: src/page_texture.cpp.o
.PHONY : src/page_texture.o

# target to build an object file
src/page_texture.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_texture.cpp.o
.PHONY : src/page_texture.cpp.o

src/page_texture.i: src/page_texture.cpp.i
.PHONY : src/page_texture.i

# target to preprocess a source file
src/page_texture.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_texture.cpp.i
.PHONY : src/page_texture.cpp.i

src/page_texture.s: src/page_texture.cpp.s
.PHONY : src/page_texture.s

# target to generate assembly for a file
src/page_texture.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_texture.cpp.s
.PHONY : src/page_texture.cpp.s

src/page_transform.o: src/page_transform.cpp.o
.PHONY : src/page_transform.o

# target to build an object file
src/page_transform.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_transform.cpp.o
.PHONY : src/page_transform.cpp.o

src/page_transform.i: src/page_transform.cpp.i
.PHONY : src/page_transform.i

# target to preprocess a source file
src/page_transform.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_transform.cpp.i
.PHONY : src/page_transform.cpp.i

src/page_transform.s: src/page_transform.cpp.s
.PHONY : src/page_transform.s

# target to generate assembly for a file
src/page_transform.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_transform.cpp.s
.PHONY : src/page_transform.cpp.s

src/page_utility.o: src/page_utility.cpp.o
.PHONY : src/page_utility.o

# target to build an object file
src/page_utility.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_utility.cpp.o
.PHONY : src/page_utility.cpp.o

src/page_utility.i: src/page_utility.cpp.i
.PHONY : src/page_utility.i

# target to preprocess a source file
src/page_utility.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_utility.cpp.i
.PHONY : src/page_utility.cpp.i

src/page_utility.s: src/page_utility.cpp.s
.PHONY : src/page_utility.s

# target to generate assembly for a file
src/page_utility.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_utility.cpp.s
.PHONY : src/page_utility.cpp.s

src/page_window.o: src/page_window.cpp.o
.PHONY : src/page_window.o

# target to build an object file
src/page_window.cpp.o:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_window.cpp.o
.PHONY : src/page_window.cpp.o

src/page_window.i: src/page_window.cpp.i
.PHONY : src/page_window.i

# target to preprocess a source file
src/page_window.cpp.i:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_window.cpp.i
.PHONY : src/page_window.cpp.i

src/page_window.s: src/page_window.cpp.s
.PHONY : src/page_window.s

# target to generate assembly for a file
src/page_window.cpp.s:
	$(MAKE) -f CMakeFiles/PAGE.out.dir/build.make CMakeFiles/PAGE.out.dir/src/page_window.cpp.s
.PHONY : src/page_window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... PAGE.out"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/page_debug.o"
	@echo "... src/page_debug.i"
	@echo "... src/page_debug.s"
	@echo "... src/page_dof.o"
	@echo "... src/page_dof.i"
	@echo "... src/page_dof.s"
	@echo "... src/page_graphics.o"
	@echo "... src/page_graphics.i"
	@echo "... src/page_graphics.s"
	@echo "... src/page_joint.o"
	@echo "... src/page_joint.i"
	@echo "... src/page_joint.s"
	@echo "... src/page_matrix.o"
	@echo "... src/page_matrix.i"
	@echo "... src/page_matrix.s"
	@echo "... src/page_mesh.o"
	@echo "... src/page_mesh.i"
	@echo "... src/page_mesh.s"
	@echo "... src/page_parser.o"
	@echo "... src/page_parser.i"
	@echo "... src/page_parser.s"
	@echo "... src/page_texture.o"
	@echo "... src/page_texture.i"
	@echo "... src/page_texture.s"
	@echo "... src/page_transform.o"
	@echo "... src/page_transform.i"
	@echo "... src/page_transform.s"
	@echo "... src/page_utility.o"
	@echo "... src/page_utility.i"
	@echo "... src/page_utility.s"
	@echo "... src/page_window.o"
	@echo "... src/page_window.i"
	@echo "... src/page_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

